services:
  migrate:
    build:
      context: .
      dockerfile: Dockerfile
      target: migrator
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB}_dev?schema=public"
    networks:
      - prod_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB}_dev?schema=public"
      PORT: "3001"
    networks:
      - prod_network

networks:
  prod_network:
    external: true
    name: fc_tournament_default
