ALTER TABLE "Player" ADD COLUMN "isDisabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Player" ADD COLUMN "isDisqualified" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Player" ADD COLUMN "canEnterScore" BOOLEAN NOT NULL DEFAULT true;
